@startuml
'https://plantuml.com/class-diagram

class Chromosome {
{static}+MAX_SHAPES: int
{static}+MAxpoints: int
+DNA:Shape[]
{static}+IMWIDTH: int
{static}+IMHEIGHT: int
{static}+target: BufferedImage
{static}+NORM_COEFF:long
-random : Random
{static}-inputFile:String

+Chromosome()
+Chromosome(Chromosome copy)
{static}+passGeneMutation(Chromosome from, Chromosome to, int index):void
+mutate():int
{static}+drawDNA(Chromosome ch): BufferedImage
{static}computeFitness(BufferedImage test): long
{static}+setTarget(String file):void
{static}+saveToFile(Chromosome c, int gen): void
{static}+main(String[] args):void


}
class  GUI  {
-frame:JFrame
{static}-textFieldOpen: JTextField
{static}-TextFieldSave: JTextField
{static}- t1:Thread
{static}-lblGenVar: JLabel
{static}-lblimpVar : JLabel
{static}- lblFitnessVal :JLabel
{static}- lblimage2:JLabel

{static}- BetterFilePath:String

{static}- GenVal:long
{static}- ImpVal:long
{static}- FitnessVal:double
{static}- OldFitness :double
{static}- NewFitness :double

{static}+ void main(String[] args)
+GUI()
- start() :void
- stop():void
-initialize() : void
+paint(Graphics g):void
{static}+ FileSaveDialog(): String
{static}+ FileOpenDialog():String
{static}+ Compare(String PathOri): void
{static}- setText(final JLabel label, final String text):void
{static}+ getFitnessVal():double
{static}+ setFitnessVal(double fitnessVal):void
{static}+ BetterFilePath(String Path):void
- paint():void
}


class Shape {
+ color: Color
+ polygon : Polygon
+ Shape(Color color, Polygon polygon)
+ Shape(Shape shape)
+ print(): void
+ toString(): String
}


@enduml